### ISSUE TITLE
Error fetching now playing movies

### ISSUE THREAD

**Issue by thymon13** [Tueti/MMM-MovieListings#16]
Hello,

Nothing is displayed.
Here is the NODE.js error

```
[ERROR] Error fetching now playing movies: TypeError: Cannot read properties of undefined (reading 'slice')
0|mm       |     at Class.fetchMovieList (/home/pi/MagicMirror/modules/MMM-MovieListings/node_helper.js:37:58)
0|mm       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

I don't know anything about NODE.js. If you could help me?

I thank you in advance.

**Comment by Tueti** [comment]
Hi @thymon13,

Could you provide a bit more insights? Which version of MagicMirror are you running? Are you displaying the movies as 'list'?

**Comment by Tueti** [comment]
Hi @thymon13,

I did resolve some bugs that creeped in with v1.1.0 in the latest v1.2.0. Could you please update the module and check if it runs properly again.

If those issue pop up again, please re-open this issue!

**Comment by thymon13** [comment]
Hello,

Same issue ;

`[ERROR] Error fetching now playing movies: TypeError: Cannot read properties of undefined (reading 'slice')
0|mm       |     at Class.fetchMovieList (/home/pi/MagicMirror/modules/MMM-MovieListings/node_helper.js:37:58)
0|mm       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) `

`cat ~/MagicMirror/package.json | grep version`
`	"version": "2.30.0",`
